- name: Installing VIM
  apt: pkg=vim state=present

- name: create Jonas
  user:
    name: jonas
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    group: root
